mysql:
  host: 127.0.0.1
  port: 3306
  db: blog
  user: root
  config: charset=utf8mb4&parseTime=True&loc=Local
  password: wangkh
  log_level: dev

logger:
  level: info
  prefix: '[gvb]'
  director:  log
  show_line: true
system:
  host: "127.0.0.1"
  port: 8080
  env: release
